### ISSUE TITLE
The AWS IoT "Connect A Device" Screen does NOT have an "Other" radio button option

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#1]
Following these steps: "Please make selections as described in the above screenshots. We will let the AWS IoT service create a certificate and the corresponding policy for us. Then click on Generate Certificate and Policy." ...  I don't get an "Other" radio button option, only the options seen below.  
![screenshot 23](https://cloud.githubusercontent.com/assets/64202/10463089/486ab3f4-7197-11e5-8fd7-598a8cce6d00.png)

**Comment by truedat101** [comment]
Please modify your docs to either describe a work around, fix, or contact AWS to find out what's up.

**Comment by nikitanerkar** [comment]
Hi,
Thanks for pointing that out.
Please following steps mentioned below,
- Select Embedded C and click on 'Generate Certificate and Policy'. This will generate certificate, private and public key.
- Download and store the private key and the certificate that has been generated. These will then be configured in our starter kit. The starter kit will use this certificate to authenticate itself with the AWS IoT service.

Please resume with the steps mentioned in Getting Started Guide

**Comment by truedat101** [comment]
Great, will follow up and let you know the result.  Thank you.

**Comment by truedat101** [comment]
Alternate steps work.  Use Embedded-C instead of "Other.
