### ISSUE TITLE
Document Factory Reset for board if that is possible

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#10]
Would be good to offer steps for factory reset (if that is possible with this SDK and configuration)/

**Comment by kedars** [comment]
This is documented here: https://github.com/marvell-iot/aws_starter_sdk/wiki/Getting%20Started%20Guide#reset-to-factory-defaults

**Comment by truedat101** [comment]
That reset is only dealing with the aws demo firmware, correct? This resets back to the clean demo state, or does it actually move back to a recovery image?

**Comment by rahulgm** [comment]
No, it programs the entire flash which includes, along with AWS starter demo, other components such as bootloader, wifi firmware, configuration data etc.

**Comment by BenoitEthier** [comment]
Pressing and holding the GPIO24 (lambda) for 10 secondes do not bring me de factory default! The documention is wrong or I have faulty biard?
