### ISSUE TITLE
Building Firmware Images On Windows gets build error

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#11]
Following "Building Firmware Images" instructions, I get a multiple target patterns error.

Make version is:
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-pc-mingw32

```
{lamb} make APP=sample_apps/hello_world
process_begin: CreateProcess(NULL, /usr/bin/mkdir -p bin/wmsdk/external/aws_iot/aws_iot_src/protocol/mqtt/aws_iot_embedded_client_wrapper/ bin/wmsdk/external/aws_iot/aws_iot_src/protocol/mqtt/aws_iot_embedded_client_wrapper/platform_wmsdk/ bin/wmsdk/external/aws_iot/aws_iot_src/shadow/ bin/wmsdk/external/aws_iot/aws_iot_src/utils/ bin/wmsdk/external/aws_iot/aws_mqtt_embedded_client_lib/MQTTClient-C/src/ bin/wmsdk/external/aws_iot/aws_mqtt_embedded_client_lib/MQTTPacket/src/ bin/wmsdk/external/freertos/Source/ bin/wmsdk/external/freertos/Source/portable/GCC/ARM_CM3/ bin/wmsdk/external/freertos/Source/portable/MemMang/ bin/wmsdk/external/lwip/contrib/port/FreeRTOS/wmsdk/ bin/wmsdk/external/lwip/src/api/ bin/wmsdk/external/lwip/src/core/ bin/wmsdk/external/lwip/src/core/ipv4/ bin/wmsdk/external/lwip/src/core/ipv6/ bin/wmsdk/external/lwip/src/netif/ bin/C:/Users/DavidJ/dev/repos/aws_starter_sdk.git/sample_apps/hello_world/ bin/C:/Users/DavidJ/dev/repos/aws_starter_sdk.git/sample_apps/hello_world/src/, ...) failed.
build/rules.mk:55: *** multiple target patterns.  Stop.

**Comment by rahulgm** [comment]
Currently we are supporting GnuWin32 platform for SDK build on Windows. MinGW and Cygwin support are currently experimental. 

From your logs, it seems you are using mingw. Can you please try the build using GnuWin32 packages? You can find the instructions for GnuWin32 setup at https://github.com/marvell-iot/aws_starter_sdk/wiki/Windows%20Development%20Host%20Setup 

Also make sure that mingw or cygwin installation path is removed from system path to avoid any interference.

Please let us know if this satisfies your requirement.
