### ISSUE TITLE
getting started guide 'connect a device' page not consistent with options

### ISSUE THREAD

**Issue by niknaknet** [marvell-iot/aws_starter_sdk#12]
hi,

when working through the getting started guide, the 'connect a device' page on the AWS IoT console is shown to have an 'other' option.

this option does not exist, and AWS support say it's not going to.  Can you update the document with the correct options?

Nick

**Comment by nikitanerkar** [comment]
Please select Embedded C option and create the certificate and keys.
Sorry for the inconvenience. We will update the document. Thanks!

**Comment by anujdeshpande** [comment]
@niknaknet thanks ! Fixed it in the documentation
https://github.com/marvell-iot/aws_starter_sdk/wiki/Getting-Started-Guide#configuring-your-aws-iot-service
