### ISSUE TITLE
There is no "other" selection while trying to connect a device

### ISSUE THREAD

**Issue by macksburg** [marvell-iot/aws_starter_sdk#13]
The instructions say to click on connect a device.  On that screen it shows an "other" option to select.  Other is not showing up.  I see the following three options. 

Embedded C
NodeJS
Arduino Yun

**Comment by nikitanerkar** [comment]
Please select Embedded C option and create the certificate and keys. Sorry for the inconvenience.

**Comment by anujdeshpande** [comment]
@macksburg thanks ! Fixed it in the documentation
https://github.com/marvell-iot/aws_starter_sdk/wiki/Getting-Started-Guide#configuring-your-aws-iot-service

**Comment by macksburg** [comment]
@anujdeshpande Thanks!
