### ISSUE TITLE
Mac OS Yosemite setup issue

### ISSUE THREAD

**Issue by bhadrip** [marvell-iot/aws_starter_sdk#19]
Hi,
I tried following [this](https://github.com/marvell-iot/aws_starter_sdk/wiki/Mac%20Development%20Host%20Setup#fix-driver-conflict) on my MAC OSX Yosemite, but i still get the 2 drivers and i am not able to erase the flash using Eclipse.
I get the following error:
```
Open On-Chip Debugger 0.9.0 (2015-06-03-11:38)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Error: libusb_claim_interface() failed with LIBUSB_ERROR_ACCESS
Error: unable to open ftdi device with vid 0403, pid 6010, description 'Dual RS232' and serial '*'
```
https://github.com/marvell-iot/aws_starter_sdk/wiki/Mac%20Development%20Host%20Setup#fix-driver-conflict

Can you please let me know, how to overcome this issue?

Thanks
Bhadri

**Comment by anujdeshpande** [comment]
@bhadrip can you check the output of the following command right after you run the 2 unload commands from the wiki. Also, make sure you restart your machine and have the board connected over usb.

    sudo dmesg

It should be something like

```
AppleUSBFTDI: fInBufPool,kMaxInBufPool 8,64
         0 [Level 5] [com.apple.message.domain com.apple.commssw.ftdi.device] [com.apple.message.signature AppleUSBFTDI] [com.apple.message.signature2 0x403] [com.apple.message.signature3 0x6010] [com.apple.message.summarize YES]
AppleUSBFTDI: Version number - 5.0.0, Input buffers 8, Output buffers 16

```

**Comment by bhadrip** [comment]
Hi @anujdeshpande ,

I don't see any message with `sudo dmesg` associated with FTDI. It does not unload or load.
I am working with a Windows machine to overcome this problem temporarily.

Thanks
Bhadri

**Comment by poorboy44** [comment]
Hi @anujdeshpande,

I also have the same issue.  I can't get the kext to unload or load.  I am working on Mac OSX Yosemite.  Please advise -- this is blocking further progress on my project.

Scotty

**Comment by anujdeshpande** [comment]
Hey @poorboy44 Can you try kext unload command without the `-p` flag ?

**Comment by poorboy44** [comment]
I get the following 

```
[snelson ~]$ sudo kextutil -b com.apple.driver.AppleUSBFTDI AppleUSBEFTDI-6010-1
Password:
AppleUSBEFTDI-6010-1 not of type 'kext'.
usage: kextutil [options] [--] [kext] ...

use kextutil -help for an explanation of each option
```

**Comment by poorboy44** [comment]
I get the following:

```
[snelson ~]$ sudo kextunload  -b com.apple.driver.AppleUSBFTDI
(kernel) Kext com.apple.driver.AppleUSBFTDI not found for unload request.
Failed to unload com.apple.driver.AppleUSBFTDI - (libkern/kext) not found.
```

**Comment by anujdeshpande** [comment]
Can you also share the output of `lsusb` ? Thanks

**Comment by poorboy44** [comment]
```
[snelson ~]$ ls -l  /dev/tty.usbserial*
crw-rw-rw-  1 root  wheel   18,   0 Jan  1 12:15 /dev/tty.usbserial-00001014A
crw-rw-rw-  1 root  wheel   18,   2 Jan  1 12:15 /dev/tty.usbserial-00001014B
```

**Comment by poorboy44** [comment]
Hi @anujdeshpande 
Any update? I tried upgrading to OSX El Capitan 10.11.2 but I'm having the same issues. Here's the error I get when I try to flash:

```
[snelson aws_starter_sdk (master)]$ sudo wmsdk/tools/OpenOCD/flash.py --mcufw ./bin/mw302_rd/hello_world.bin
Writing MCU firmware to flash
Using OpenOCD interface file ftdi.cfg
Open On-Chip Debugger 0.9.0 (2015-12-16-16:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
flash
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Error: libusb_claim_interface() failed with LIBUSB_ERROR_ACCESS
Error: unable to open ftdi device with vid 0403, pid 6010, description 'Dual RS232' and serial '*'

Writing MCU firmware to flash failed...
```

**Comment by anujdeshpande** [comment]
Can you try doing the following : 

1. Reboot
2. Connect the board to your Mac 
3. Run `ls /dev/tty.*` and save the output
4. `sudo kextunload -b com.apple.driver.AppleUSBFTDI`
5. `sudo kextutil -b com.apple.driver.AppleUSBFTDI -p AppleUSBEFTDI-6010-1` 
6. Run `ls /dev/tty.*` and save the output
7. Run `libusb-config --version` and save the output

Please paste the output here so that I can try and debug the issue. Also, make sure that you are running commands 4 and 5 in the order mentioned above.

**Comment by poorboy44** [comment]
```
[snelson ~]$ ls -l /dev/tty.*
crw-rw-rw-  1 root  wheel   18,   0 Jan  1 18:29 /dev/tty.Bluetooth-Incoming-Port
crw-rw-rw-  1 root  wheel   18,   2 Jan  1 18:30 /dev/tty.usbserial-00001014A
crw-rw-rw-  1 root  wheel   18,   4 Jan  1 18:30 /dev/tty.usbserial-00001014B
[snelson ~]$ sudo kextunload -v -b com.apple.driver.AppleUSBFTDI
Password:
(kernel) Kext com.apple.driver.AppleUSBFTDI not found for unload request.
Failed to unload com.apple.driver.AppleUSBFTDI - (libkern/kext) not found.
[snelson ~]$ sudo kextutil -v -b com.apple.driver.AppleUSBFTDI -p AppleUSBEFTDI-6010-1
Defaulting to kernel file '/System/Library/Kernels/kernel'
/System/Library/Extensions/AppleUSBFTDI.kext appears to be loadable (not including linkage for on-disk libraries).
Loading /System/Library/Extensions/AppleUSBFTDI.kext.
/System/Library/Extensions/AppleUSBFTDI.kext successfully loaded (or already loaded).
[snelson ~]$ ls -l /dev/tty.*
crw-rw-rw-  1 root  wheel   18,   0 Jan  1 18:29 /dev/tty.Bluetooth-Incoming-Port
crw-rw-rw-  1 root  wheel   18,   2 Jan  1 18:30 /dev/tty.usbserial-00001014A
crw-rw-rw-  1 root  wheel   18,   4 Jan  1 18:30 /dev/tty.usbserial-00001014B
[snelson ~]$ libusb-config --version
0.1.12
```

**Comment by truedat101** [comment]
Throwing #6 into the discussion, as this was closed out but was basically the same set of issues.  Is there something else claiming the interface?

**Comment by poorboy44** [comment]
How can I check that?

**Comment by truedat101** [comment]
Hrrmmm, that was what I was wondering.  On posix systems, you use lsof.  I don't know on Mac OS X.  I thought maybe I had something on my mac that was hogging my interfaces, like a cell phone sync software or maybe some other driver that I'd installed for some IoT device.  However, without instructions on how to debug the possibilities or variations on the Mac, it always makes the Mac a bit less desirable a dev platform for serious work beyond iOS.  The Linux setup for this, and using OpenOCD is generally flawless.

**Comment by truedat101** [comment]
In any case, I think #6 should have been kept open as the problem was unresolved at closure time (I gave up on the issue).

**Comment by anujdeshpande** [comment]
@poorboy44 Can you try out `sudo kextload -b com.apple.driver.AppleUSBFTDI`. This is manually trying to load the driver for FTDI. 

@truedat101 your comment has linked #6 to this discussion (thanks!), so that should redirect anyone who finds themselves there.

**Comment by poorboy44** [comment]
Still having errors.  Can we jump on a Google Hangout to debug? My email is poorboy44@gmail.com

```
[snelson aws_starter_sdk (master)]$ sudo kextunload -p -b com.apple.driver.AppleUSBFTDI
[snelson aws_starter_sdk (master)]$ sudo kextutil -b com.apple.driver.AppleUSBFTDI -p AppleUSBEFTDI-6010-1
[snelson aws_starter_sdk (master)]$ sudo kextload -b com.apple.driver.AppleUSBFTDI
[snelson aws_starter_sdk (master)]$ ls /dev/tty.* 
/dev/tty.Bluetooth-Incoming-Port /dev/tty.usbserial-00001014A     /dev/tty.usbserial-00001014B
[snelson aws_starter_sdk (master)]$ sudo wmsdk/tools/OpenOCD/flash.py --mcufw ./bin/mw302_rd/hello_world.bin
Writing MCU firmware to flash
Using OpenOCD interface file ftdi.cfg
Open On-Chip Debugger 0.9.0 (2015-12-16-16:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
flash
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Error: libusb_claim_interface() failed with LIBUSB_ERROR_ACCESS
Error: unable to open ftdi device with vid 0403, pid 6010, description 'Dual RS232' and serial '*'

Writing MCU firmware to flash failed...
```

**Comment by anujdeshpande** [comment]
@poorboy44 We have a gitter channel which is quite active

https://gitter.im/marvell-iot/scu_aws_starter_sdk

**Comment by anujdeshpande** [comment]
So this issue was closed by removing the conflicting FTDI drivers that were getting loaded by default.
