### ISSUE TITLE
Marvell IoT Starter Kit device when powered over USB does not advertise a WiFi network

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#2]
Instructions suggest:  aws_starter-WXYZ

should be found.  I don't see it on from my Mac WiFi or from a phone.  Perhaps wrong firmware on Marvell IoT device?  How would I know?

**Comment by Broncobob76** [comment]
When attempting to connect over WiFI using aws_Starter-FCBA I am prompted for my security key. I cannot find the wifi security key value anywhere in your documentation. This should be added to the quick start documentation page.

**Comment by nikitanerkar** [comment]
It is marvellwm. Sorry for the inconvenience. We will update the document.

**Comment by truedat101** [comment]
@nikitanerkar  no, it's unfortunate but no matching aws_starter_* SSIDs show up.  LED on gpio_40 (yellow) blinks at a slow interval.  Other lights are solid.

**Comment by kedars** [comment]
It seems some kits contained an older version of the AWS starter demo firmware. Could you please try with the latest flashing guidelines: https://github.com/marvell-iot/aws_starter_sdk/wiki/Flashing-the-Starter-Kit

**Comment by truedat101** [comment]
@kedars excellent.  I will get onto trying this during the remainder of the week.  I will be in touch for result so we can close this item.

**Comment by truedat101** [comment]
So it sounds like this bug is related to the old firmware.  I think you can close this.  I am still attempting the firmware update because I had an older pre-release kit.
