### ISSUE TITLE
IoT device not launching the aws_starter-WXYZ network to connect to

### ISSUE THREAD

**Issue by vikramsb2k** [marvell-iot/aws_starter_sdk#24]
Hello,

I have been trying to get started with the Marvell MW302 IoT starter kit that I bought on amazon but seems like when I connect it to the PC, it is supposed to launch its "own" network which i should be able to connect to, but it is not launching that network and i dont see it on my wireless network list.

Can you please help suggest what might be going wrong here?

Thanks
VIk

**Comment by msaksena** [comment]
Vik: 

It seems like some of the kits shipped with old firmware. Please flash the kit with the latest firmware. Instructions available at: https://github.com/marvell-iot/aws_starter_sdk/wiki/Flashing-the-Starter-Kit. 

Manas

**Comment by anujdeshpande** [comment]
[lambda.zip](https://github.com/marvell-iot/aws_starter_sdk/files/111812/lambda.zip)
