### ISSUE TITLE
How to write code on device?

### ISSUE THREAD

**Issue by abhirocks550** [marvell-iot/aws_starter_sdk#29]
I am successfully able to connect the device to AWS IoT cloud and on and off LED from Aws.
Now i want to write hello world program on device. Where do i write program and upload that on device?
Like in Arduino we use Arduino IDE to create and upload program to device.How can i do that with MW302 device?

Can somebody help?Thanks.

**Comment by anujdeshpande** [comment]
Hello @abhirocks550 
Please check the following video tutorial, it shows how to upload code using the command line : 
https://www.youtube.com/playlist?list=PLIYfgNqDE8r3Qhz1qDWJFI13GtgOjYdyz

You can also check out the [wiki](https://github.com/marvell-iot/aws_starter_sdk/wiki) where there are instructions for multiple operating systems.

To give a rough overview, you will have to install a cross compiler toolchain, and run something like

``` make APP=sample_apps/hello_world```

This will create the binary file in the bin/ folder in your cloned repo.

If you need additional help you can join the gitter channel : http://gitter.im/marvell-iot/aws_starter_sdk

**Comment by abhirocks550** [comment]
Thanks for quick reply @anujdeshpande . I will look into it.

**Comment by abhirocks550** [comment]
I do not have much knowledge about embedded c. I tried make APP=sample_apps/hello_world command but got following error

make[1]: Entering directory `/home/abhijit/Desktop/AWS_IOT/aws_starter_sdk'
make[1]: arm-none-eabi-gcc: Command not found
make[1]: *** [bin//home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/sample_apps/hello_world/src/main.o] Error 127
make[1]: Leaving directory `/home/abhijit/Desktop/AWS_IOT/aws_starter_sdk'
make: *** [do_the_build] Error 2

Please help.Can you provide some resources which i prerequisite for this?

**Comment by anujdeshpande** [comment]
@abhirocks550 Please follow the steps given on https://github.com/marvell-iot/aws_starter_sdk/wiki/Development-Host-Setup to install the required tools on your machine

**Comment by abhirocks550** [comment]
@anujdeshpande  i follwed the above steps and successfully executed command and it created following files :
 
[axf] /home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/bin/mw302_rd/hello_world.axf
 [bin] /home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/bin/mw302_rd/hello_world.bin

but i am not able see output in minicom. What else steps are needed to see output? 
Thanks.

**Comment by anujdeshpande** [comment]
@abhirocks550 did you upload the generated .bin file to your board?

**Comment by abhirocks550** [comment]
How can i upload that .bin file to board?

**Comment by anujdeshpande** [comment]
You can find more info on how to upload the generated files on the wiki : 
https://github.com/marvell-iot/aws_starter_sdk/wiki/Flashing%20the%20Starter%20Kit

**Comment by abhirocks550** [comment]
After entering these commands 

$ sudo wmsdk/tools/OpenOCD/flash.py --mcufw sudo wmsdk/tools/OpenOCD/flash.py --mcufw /home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/bin/mw302_rd/hello_world.bin
$ sudo wmsdk/tools/OpenOCD/flash.py -r

minicom not able to connect to ttyUSB1 and even after i press reset button on device nothing changed:-(

**Comment by anujdeshpande** [comment]
It should be
```
sudo wmsdk/tools/OpenOCD/flash.py --mcufw /home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/bin/mw302_rd/hello_world.bin 
```
Can you also paste the output of your command here.

**Comment by abhirocks550** [comment]
aws_starter_sdk$ sudo wmsdk/tools/OpenOCD/flash.py --mcufw /home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/bin/mw302_rd/hello_world.bin

## Ouput of this command is 

Writing MCU firmware to flash...
Using OpenOCD interface file ftdi.cfg
Open On-Chip Debugger 0.9.0 (2015-07-15-15:28)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
flash
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Info : clock speed 3000 kHz
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
Info : wmcore.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x00007f14 msp: 0x20001000
auto erase enabled
Info : Found flash device 'win w25q32fv' ID 0x001640ef
wrote 65536 bytes from file /home/abhijit/Desktop/AWS_IOT/aws_starter_sdk/bin/mw302_rd/hello_world.bin in 0.859195s (74.488 KiB/s)
shutdown command invoked
Writing MCU firmware to flash done...
================================================================
sudo wmsdk/tools/OpenOCD/flash.py -r
## ouput of second command 

Resetting board...
Using OpenOCD interface file ftdi.cfg
Open On-Chip Debugger 0.9.0 (2015-07-15-15:28)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Info : clock speed 3000 kHz
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
Info : wmcore.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
shutdown command invoked
Resetting board done...

**Comment by anujdeshpande** [comment]
What minicom command and port did you use to connect to your board ?
Can you paste the output of ls /dev/tty* ?

**Comment by abhirocks550** [comment]
I used sudo minicom -s command 

##Output 

Welcome to minicom 2.7

OPTIONS: I18n                                                                
Compiled on Jan  1 2014, 17:13:19.                                           
Port /dev/ttyUSB1, 15:17:13                                                  
                                                                             
Press CTRL-A Z for help on special keys                                      
                                                               

##Ouput of ls /dev/tty*

/dev/tty    /dev/tty16	/dev/tty24  /dev/tty32	/dev/tty40  /dev/tty49	/dev/tty57  /dev/tty8	    /dev/ttyS14  /dev/ttyS22  /dev/ttyS30
/dev/tty0   /dev/tty17	/dev/tty25  /dev/tty33	/dev/tty41  /dev/tty5	/dev/tty58  /dev/tty9	    /dev/ttyS15  /dev/ttyS23  /dev/ttyS31
/dev/tty1   /dev/tty18	/dev/tty26  /dev/tty34	/dev/tty42  /dev/tty50	/dev/tty59  /dev/ttyprintk  /dev/ttyS16  /dev/ttyS24  /dev/ttyS4
/dev/tty10  /dev/tty19	/dev/tty27  /dev/tty35	/dev/tty43  /dev/tty51	/dev/tty6   /dev/ttyS0	    /dev/ttyS17  /dev/ttyS25  /dev/ttyS5
/dev/tty11  /dev/tty2	/dev/tty28  /dev/tty36	/dev/tty44  /dev/tty52	/dev/tty60  /dev/ttyS1	    /dev/ttyS18  /dev/ttyS26  /dev/ttyS6
/dev/tty12  /dev/tty20	/dev/tty29  /dev/tty37	/dev/tty45  /dev/tty53	/dev/tty61  /dev/ttyS10     /dev/ttyS19  /dev/ttyS27  /dev/ttyS7
/dev/tty13  /dev/tty21	/dev/tty3   /dev/tty38	/dev/tty46  /dev/tty54	/dev/tty62  /dev/ttyS11     /dev/ttyS2	 /dev/ttyS28  /dev/ttyS8
/dev/tty14  /dev/tty22	/dev/tty30  /dev/tty39	/dev/tty47  /dev/tty55	/dev/tty63  /dev/ttyS12     /dev/ttyS20  /dev/ttyS29  /dev/ttyS9
/dev/tty15  /dev/tty23	/dev/tty31  /dev/tty4	/dev/tty48  /dev/tty56	/dev/tty7   /dev/ttyS13     /dev/ttyS21  /dev/ttyS3   /dev/ttyUSB1

**Comment by anujdeshpande** [comment]
This looks ok. What parameters did you put in for the baud rate, etc?

You could try the gpio example from the io demos sample apps directory to verify that there are no problems in uploading. This example does not require a serial console to check correctness.

**Comment by abhirocks550** [comment]
Following are parameters for minicom

A -    Serial Device      : /dev/ttyUSB1                              |
    | B - Lockfile Location     : /var/lock                                 |
    | C -   Callin Program      :                                           |
    | D -  Callout Program      :                                           |
    | E -    Bps/Par/Bits       : 115200 8N1                                |
    | F - Hardware Flow Control : Yes                                       |
    | G - Software Flow Control : No

**Comment by anujdeshpande** [comment]
https://github.com/marvell-iot/aws_starter_sdk/wiki/Linux%20Development%20Host%20Setup
Make sure that Hardware flow control is set to No

**Comment by abhirocks550** [comment]
I tried uploading gpio program on device how to i change status of LED? 
where does this gets printed " Press button 2 to toggle state of LED?And where is button 2 on device?

**Comment by anujdeshpande** [comment]
Please refer this image
https://raw.githubusercontent.com/marvell-iot/aws_starter_sdk_wiki_images/master/RD-88MW302-A0-V2%20wo%20shield.jpeg
pb_lambda is the one that you are looking for

**Comment by abhirocks550** [comment]
I tried pressing that but nothing changes, i mean now two LED's are on i think they are near D9 and R1.
but after pressing pb_lambda nothing changes :(. I feel like i am not able to understand this. Could you provide some resources for attempting this ?

**Comment by anujdeshpande** [comment]
Can you do the following 

1. Flash the blob from the releases section using flash.py -f
2. Flash your hello_world.bin using flash.py --mcufw
3. Reset the board and check your minicom console

Please do these in the exact order as mentioned

**Comment by abhirocks550** [comment]
Great. Thanks alot successfully able to upload hello_world.bin and able to see output in minicom.
I am not much aware about core embedded c, if i want write such programs myself then could you provide some links or books which i need to study?
Thanks for help.
