### ISSUE TITLE
MQTT Subscriptions lost on device reconnnect

### ISSUE THREAD

**Issue by sodle** [marvell-iot/aws_starter_sdk#32]
I'm working with the AWS Starter Demo program on the Marvell MW302 board. Upon losing wireless connection, the software is able to reconnect to WiFi and to AWS, as demonstrated on line 364 of `sample_apps/aws_starter_demo/src/main.c`.

However, this causes MQTT subscription to stop working - the board is still able to publish state changes to AWS, but no longer responds to remote changes. Re-creating the subscriptions (by pasting the relevant code from lines 317 and 343-354 after line 372) seems to have no effect.

**Comment by anujdeshpande** [comment]
Is this related to #28 @nikitanerkar ?

**Comment by sodle** [comment]
Is there a way to reboot the board from code? This would allow me to work around the issue for now. Thanks.

**Comment by anujdeshpande** [comment]
@sodle unfortunately you won't be able to reboot the board from code using this SDK. We are working on pushing a fix for the MQTT issue, I'll post an update here once we do

**Comment by anujdeshpande** [comment]
@sodle We have a new aws agent now, up to date with the latest aws embedded c SDK. I am closing this issue, if you get the same issue with the new version, please open a new issue
