### ISSUE TITLE
How to read the PWM signal from the marvell board?

### ISSUE THREAD

**Issue by rkamath13** [marvell-iot/aws_starter_sdk#35]
I am trying to interface an ultrasonic sensor to the marvell board, it works on PWM.
I am trying to understand how to go about it.

any help will be appreciated!

thanks
Ramesh

**Comment by anujdeshpande** [comment]
hi @rkamath13 
You can take a look at some of the other sample apps for io https://github.com/marvell-iot/aws_starter_sdk/tree/master/sample_apps/io_demo

Your app will be similar but will include the following header file. The comments in the header file should help you get started
https://github.com/marvell-iot/aws_starter_sdk/blob/master/sdk/src/incl/sdk/drivers/mdev_gpt.h

To check out which pins you can use to interface your ultrasonic sensor you can take a look at our wiki page too
https://github.com/marvell-iot/aws_starter_sdk/wiki/Pin-map-for-Marvell-MW302-IoT-Starter-Kit

It has the list of different functions on each pin.
