### ISSUE TITLE
Interfacing Grove-Water Sensor 101020018 

### ISSUE THREAD

**Issue by Prashant-Kmr** [marvell-iot/aws_starter_sdk#38]
Hi I have written following code for interfacing Grove-Water Sensor 101020018 but values are not getting displayed for the detection of water please check it and suggest.

**sensor_water_drv.c:**

#include "wm_os.h"
#include "wmstdio.h"
#include "wmtime.h"
#include "wmsdk.h"
#include "board.h"
#include "mdev_gpio.h"
#include "mdev_pinmux.h"
#include "lowlevel_drivers.h"

#include "sensor_drv.h"
#include "sensor_water_drv.h"
#include <dht_drv.h>

#define WATER_SEN_IO		GPIO_22
#define WATER_SEN_IO_GPIO	GPIO22_GPIO22

struct io_gpio_cfg IO_1WIRE = { /* Used for 1WIRE protocol */
	.pinno = GPIO_1,
	.val = GPIO_IO_HIGH,
	.altfun = GPIO1_GPIO1,
	.pinmode = PINMODE_DEFAULT,
	.dir = GPIO_OUTPUT,
	.irqtype = GPIO_INT_DISABLE,
	.id = GPT0_ID,
	.ch = GPT_CH_1,
};

static uint8_t watr[4];
static char W_ready[16];

/*
 *********************************************************
 **** Water Sensor H/W Specific code
 **********************************************************
 */

int dht_readings(struct dht_psmvar *dht_vars)
{
	wmprintf("Water =%d\r\n",
			dht_vars->water);
	watr[3] = watr[2];
	watr[2] = watr[1];
	watr[1] = watr[0];
	watr[0] = dht_vars->water;
	if ((watr[0] == watr[1])
		&& (watr[1] == watr[2])
		&& (watr[2] != watr[3])) {
			/* Water reading is ready to post */
			sprintf(W_ready, "%d", watr[3]);
			dbg("Reporting Water = %s\r\n", W_ready);
	}
	return 0;
}

/* Basic Sensor IO initialization to be done here

	This function will be called only once during sensor registration
 */
int water_sensor_init(struct sensor_info *curevent)
{
	wmprintf("%s\r\n", __FUNCTION__);

	mdev_t *pinmux_dev, *gpio_dev;

	/* Initialize  pinmux driver */
	pinmux_drv_init();

	/* Open pinmux driver */
	pinmux_dev = pinmux_drv_open("MDEV_PINMUX");

	/* Initialize GPIO driver */
	gpio_drv_init();

	/* Open GPIO driver */
	gpio_dev = gpio_drv_open("MDEV_GPIO");

	/* digital Water related init */
	dht_drv_init(&IO_1WIRE);
	dht_learn(dht_readings);

	/* Close drivers */
	pinmux_drv_close(pinmux_dev);
	gpio_drv_close(gpio_dev);

	return 0;
}

/* Sensor input from IO should be read here and to be passed
	in curevent->event_curr_value variable to the upper layer

	Respective AWS event will be reported to the cloud by
	upper sensor_driver layer

	This function will be called periodically by the upper layer
	hence you can poll your input here, and there is no need of
	callback IO interrupt, this is very usefull to sense variable
	data from analog sensors connected to ADC lines. Even this can
	be used to digital IO scanning and polling
*/
int wtrt_sensor_input_scan(struct sensor_info *curevent)
{
	if (W_ready) {
		sprintf(curevent->event_curr_value, "%d", W_ready);
		W_ready[0] = 0;
		dbg("Reported Water = %s\r\n",
				curevent->event_curr_value);
	}
	return 0;
}

struct sensor_info event_wtrt_sensor = {
	.property = "Water Sensor",
	.init = water_sensor_init,
	.read = wtrt_sensor_input_scan,
};

int water_sensor_event_register(void)
{
	return sensor_event_register(&event_wtrt_sensor);
}

**sensor_water_drv.h:**

/*
 * Custom Sensor Driver header file
 */

#ifndef __SENSOR_WATER_DRV_H__
#define __SENSOR_WATER_DRV_H__

int water_sensor_event_register(void);

/* You can declare customer sensor specific declaratio here */

#endif /* __SENSOR_WATER_DRV_H__ */

**Minicom Output:**

Build Time: Apr 29 2016 16:35:54

#### AWS STARTER DEMO ####

sensor_drv_init done
water_sensor_init
dht_drv_init
Sensor event Water Sensor(0x20000740) is registered sucessfully
Water =0
Water =0
Connected successfully to the configured network
Water =0
Water =0
Cloud Started
delta topic $aws/things/Led1/shadow/update/delta
Publishing '{"state": {"reported":{"pb":0,"pb_lambda":0,"led":0}}}' to AWS
Water =0
Publishing '{"state": {"reported":{"Water Sensor":536936724,"led":1}}}' to AWS
Water =0
Water =0

**Comment by anujdeshpande** [comment]
hi @Prashant-Kmr as discussed on Gitter, this is an issue with the sensor or wiring, and has nothing to do with the aws_starter_sdk.

Also, the sensor drivers have been implemented in a different repo.
https://github.com/prafullawadaskar/aws_starter_sdk/
So raising an issue on this repo will mislead other people.

**Comment by Prashant-Kmr** [comment]
Hi,

thank you for response. Where do I get help on that issue?? As I find
issues are not allowed to open at
https://github.com/prafullawadaskar/aws_starter_sdk/ . Is this repo not
related to Marvell SDK??
