### ISSUE TITLE
SDK for EZ-Connect / 88MC200+88W8801

### ISSUE THREAD

**Issue by wind-rider** [marvell-iot/aws_starter_sdk#40]
While this SDK does offer support for 88MC300, looking at [this config file](https://github.com/marvell-iot/aws_starter_sdk/blob/master/.config#L8-L11) it seems there is no support for 88MC200.

Could you please add support for the 88MC200+88W8801 pair?

**Comment by anujdeshpande** [comment]
Hi @wind-rider the 88MC200 board is not openly available. This SDK is targeted for people who are using the AWS starter kit https://www.amazon.com/Globalscale-MW302-IoT-Starter-Powered/dp/B0168DLQHI/ref=sr_1_1 which is more widely available.
