### ISSUE TITLE
flash.py tools path in wiki don't match actual master

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#43]
https://github.com/marvell-iot/aws_starter_sdk/wiki/Flashing-the-Starter-Kit

sudo wmsdk/tools/OpenOCD/flash.py

is really:

sudo sdk/tools/OpenOCD/flash.py

**Comment by anujdeshpande** [comment]
@truedat101 Thanks for pointing out ! It has been fixed in the wiki

Also, we are in the process of moving the docs from the wiki to  http://marvell-iot.github.io/
