### ISSUE TITLE
flash.py should have 744 permissions if it is intended to be used according to wiki

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#44]
either document use with python flash.py

or make sure that flash.py is set to permission 744 in the release

**Comment by anujdeshpande** [comment]
Hi @truedat101 thanks for pointing it out !
https://github.com/marvell-iot/aws_starter_sdk/commit/59a957e996d2b952d0a3c027b715414909985f98
This commit fixes it, 755 for `flash.py` as well as `openocd.py`. `ramload.py` already had it set correctly.
There's a new release that's coming soon, I'll bundle these changes with that. Will keep this  open for the time being.
