### ISSUE TITLE
Mac Open OCD Setup doesn't work on OS X 10.11.1 when trying to do a firmware update

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#6]
After following these steps
https://github.com/marvell-iot/aws_starter_sdk/wiki/Mac%20Development%20Host%20Setup

Reflashing firmware fails:

\> ./wmsdk/tools/OpenOCD/flash.py -f dist/aws_starter_sdk-2015_11_04.blob

Resetting flash to factory settings
Using OpenOCD interface file ftdi.cfg
Open On-Chip Debugger 0.9.0 (2015-09-23-21:46)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
flash
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Error: libusb_claim_interface() failed with LIBUSB_ERROR_ACCESS
Error: unable to open ftdi device with vid 0403, pid 6010, description 'Dual RS232' and serial '*'

**Comment by truedat101** [comment]
The steps to avoid driver conflict were performed first:

  \> sudo kextunload -p -b com.apple.driver.AppleUSBFTDI
  \> sudo kextutil -b com.apple.driver.AppleUSBFTDI -p AppleUSBEFTDI-6010-1

**Comment by ameyinamdar** [comment]
Can you please check the libusb library version? 0.1.12 (package version 1.0.19_0) is known to work which can be installed using macports or brew on 10.11.1.

$ sudo port install libusb @1.0.19_0

$ sudo port activate libusb @1.0.19_0

$ libusb-config --version
0.1.12

**Comment by truedat101** [comment]
$brew list libusb
/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0/libusb.h
/usr/local/Cellar/libusb/1.0.20/lib/libusb-1.0.0.dylib
/usr/local/Cellar/libusb/1.0.20/lib/pkgconfig/libusb-1.0.pc
/usr/local/Cellar/libusb/1.0.20/lib/ (2 other files)

**Comment by ameyinamdar** [comment]
Can you please try using 1.0.19 version of libusb?

**Comment by truedat101** [comment]
I will try to figure out how to get brew to switch back to an older version of libusb.  Note, 99% of the people installing today on a newly upgrades mac os X 10.11 using brew will not end up with a backport of libusb, but the latest supported version.  Switching versions is non-trivial.

**Comment by truedat101** [comment]
And trying to have mac ports and brew on the same system is a non-option.

**Comment by truedat101** [comment]
After some effort, I figured out how to rollback to an older version of brew and install libusb 1.0.19.  Exact same result.

**Comment by truedat101** [comment]
I am going to roll forward to the default libusb 1.0.20.  If this is to work at all, we have to get it working with the latest version of brew.

**Comment by truedat101** [comment]
release info for my mac os x host: Darwin name.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

**Comment by anujdeshpande** [comment]
I have the following setup and things work for me. 
```
➜  ~  uname -a
Darwin Anujs-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64
➜  ~ sudo kextunload -p -b com.apple.driver.AppleUSBFTDI
➜  ~ sudo kextutil -b com.apple.driver.AppleUSBFTDI -p AppleUSBEFTDI-6010-1
➜  ~  libusb-config --version
0.1.12
➜  ~  openocd --version
Open On-Chip Debugger 0.9.0 (2015-09-23-21:46)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
➜  ~  brew --version
0.9.5 (git revision c6fa6; last commit 2015-11-06)
➜  ~  brew list libusb
/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0/libusb.h
/usr/local/Cellar/libusb/1.0.20/lib/libusb-1.0.0.dylib
/usr/local/Cellar/libusb/1.0.20/lib/pkgconfig/libusb-1.0.pc
/usr/local/Cellar/libusb/1.0.20/lib/ (2 other files)
```
So it might not be a libusb version issue.

**Comment by truedat101** [comment]
$ls /dev/tty.*
/dev/tty.Bluetooth-Incoming-Port	/dev/tty.usbserial-00001014B
/dev/tty.usbserial-00001014A

**Comment by anujdeshpande** [comment]
So there should be only one usbserial if the kext unload was successful. Can you check dmesg output when you run those 2 commands ?
Also, the unloading has to be done each time you boot your mac, but only once per session.

**Comment by truedat101** [comment]
Agreed. I have some ios stuff running.  Let me see what' up.

**Comment by truedat101** [comment]
Hrm.. no output during those commands.

I'm thinking there are so many reasons Apple can be a lost cause.  I've got some mobile phone daemon that I can't kill.  I'll do a little research to see what it might be.

**Comment by truedat101** [comment]
It's probably safe assume this is due to something else claiming the interface.  Whatever the case, it should be noted somewhere under the Mac OS X Host Setup section troubleshooting some of the steps above to sort out what the problem is.  I don't have a root cause, but I suspect somesoftware I have is sitting on the usb interface.

**Comment by anujdeshpande** [comment]
@truedat101 Added some more debug info from this thread to the [wiki](https://github.com/marvell-iot/aws_starter_sdk/wiki/Mac-Development-Host-Setup#fix-driver-conflict) 
Closing this issue now, but please let us know what was claiming the interface when you figure it out.

**Comment by mintisan** [comment]
@anujdeshpande It works for me to use your way, thanks.

```
➜  ~ sudo kextunload -p -b com.apple.driver.AppleUSBFTDI
➜  ~ sudo kextutil -b com.apple.driver.AppleUSBFTDI -p AppleUSBEFTDI-6010-1
```

some versions as below:
```
➜  freedom-e-sdk git:(master) ✗ uname -a
Darwin MacBookPro.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
➜  freedom-e-sdk git:(master) ✗ libusb-config --version
0.1.12
➜  freedom-e-sdk git:(master) ✗ openocd --version
Open On-Chip Debugger 0.10.0-dev-g9bab078-dirty (2017-04-03-18:55)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
➜  freedom-e-sdk git:(master) ✗ brew --version
Homebrew 1.1.12
Homebrew/homebrew-core (git revision 6fac4; last commit 2017-04-03)
➜  freedom-e-sdk git:(master) ✗ brew list libusb
/usr/local/Cellar/libusb/1.0.21/include/libusb-1.0/libusb.h
/usr/local/Cellar/libusb/1.0.21/lib/libusb-1.0.0.dylib
/usr/local/Cellar/libusb/1.0.21/lib/pkgconfig/libusb-1.0.pc
/usr/local/Cellar/libusb/1.0.21/lib/ (2 other files)
/usr/local/Cellar/libusb/1.0.21/share/libusb/ (16 files)
➜  freedom-e-sdk git:(master) ✗ 

```

**Comment by mintisan** [comment]
@anujdeshpande but I can't use usb-uart to log message...
