### ISSUE TITLE
Doc: The Windows Development Host Setup can alternatively use cmder shell

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#7]
By using https://github.com/bliker/cmder/releases/download/v1.2/cmder.zip

one doesn't need to install the posix system system utilities.

**Comment by anujdeshpande** [comment]
This looks interesting. Trying it out in a bit.
Another approach to solving the cross platform issue is porting everything to python natively. 
We have done that for [which right now](https://github.com/marvell-iot/aws_starter_sdk/blob/master/wmsdk/tools/OpenOCD/ramload.py#L16) in the ramload script. thoughts ?

**Comment by truedat101** [comment]
Sure, python 2.7 is on mac and linux by default.  Using chocolatey command, one can easily fetch and manage windows dependencies like Python or just use the installer.

**Comment by anujdeshpande** [comment]
Thanks for the suggestion @truedat101 ! 
Closing this issue to reduce the clutter
