### ISSUE TITLE
Windows Host Firmware Update gives  LIBUSB_ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#8]
$ ./wmsdk/tools/OpenOCD/flash.py -f ./aws_starter_sdk-2015_11_04.blob
Resetting flash to factory settings
Using OpenOCD interface file ftdi.cfg
Open On-Chip Debugger 0.9.0 (2015-05-19-12:06)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
flash
adapter speed: 3000 kHz
adapter_nsrst_delay: 100
Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
jtag_ntrst_delay: 100
cortex_m reset_config sysresetreq
sh_load
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Info : clock speed 3000 kHz
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
Info : wmcore.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba00, ver: 0x4)
target state: halted
target halted due to debug-request, current mode: Thread
xPSR: 0x01000000 pc: 0x00007f14 msp: 0x20001000
auto erase enabled
Info : Found flash device 'win w25q32fv' ID 0x001640ef
wrote 1376256 bytes from file C:/Users/DavidJ/dev/repos/aws_starter_sdk.git/aws_starter_sdk-2015_11_04.blob in 18.207382s (73.816 KiB/s)
shutdown command invoked
Resetting flash to factory settings done...

**Comment by truedat101** [comment]
System is Windows 10

**Comment by anujdeshpande** [comment]
Same happens on Win8. The thing is it's not really an issue. I haven't figured out why it happens, but it does work exactly as expected.

**Comment by truedat101** [comment]
It appears to complete the steps, I think.  Is that why you say it's not really an issue?

**Comment by truedat101** [comment]
At the end of this, my 88M device I reset, but it doesn't have any blinking lights and isn't emitting a WIFI SSID.

**Comment by msaksena** [comment]
Do you have a serial console set up? If so, you should be able to see the output from the device on the console.

**Comment by truedat101** [comment]
I will try that.

**Comment by truedat101** [comment]
So I've got a "Tera Term" app connected to the device.  I don't see any serial output from the device.  Do I need to run the reflash command from an elevated shell?

**Comment by truedat101** [comment]
wondering if this board is now bricked.  I'll try the linux set up and see if that recovers the situation.  Otherwise, I think I have some new boards arriving and will use those.

**Comment by kedars** [comment]
Just to confirm: Could you verify your console settings with the console instructions that I updated on wiki. Also, could you try pressing the reset button on the kit, after the serial console is connected. 

Alternatively, since all the software is similar, I am wondering if this could be an issue with some incorrect Jumper settings, could you take a snap of the kit and attach it over here?

**Comment by truedat101** [comment]
Let's start with Jumpers:
![img_20151109_224106](https://cloud.githubusercontent.com/assets/64202/11056168/b2f8e7d4-8733-11e5-9479-718562a4b49e.jpg)

**Comment by kedars** [comment]
Hmm, all looks to be in order to me... Can you cross-check the serial-console as I mention above.

**Comment by truedat101** [comment]
Sure, when connected over serial:

Build Time: Nov  4 2015 14:24:25

#### AWS STARTER DEMO ####



* CLICK ON RESET, RELEASE *
Build Time: Nov  4 2015 14:24:25

#### AWS STARTER DEMO ####

**Comment by truedat101** [comment]
After this, I am expecting to get some blinking lights but I only have D1 and D9? leds lit solid green.

**Comment by truedat101** [comment]
I received a new unit.  It had firmware already loaded but not the AWS IOT demo firmware.  It would boot up, and displayed a blinking LED on D6 and solid on D7.  I was able to see full boot sequence via debugger.

I proceeded to perform a Flash update, per the instructions.  After this process completes, the 2 LEDs D6/D7 are dark, and no longer lit.  A reset (or pulling of power) doesn't get them to turn back on.  It would appear this sequence as performed on Windows 10 leads to a bricked device?  Can I recover from this point?
              
$ wmsdk/tools/OpenOCD/flash.py -f ./aws_starter_sdk-2015_11_04.blob             
Resetting flash to factory settings                                             
Using OpenOCD interface file ftdi.cfg                                           
Open On-Chip Debugger 0.9.0 (2015-05-19-12:06)                                  
Licensed under GNU GPL v2                                                       
For bug reports, read                                                           
        http://openocd.org/doc/doxygen/bugs.html                                
flash                                                                           
adapter speed: 3000 kHz                                                         
adapter_nsrst_delay: 100                                                        
Info : auto-selecting first available session transport "jtag". To override use 
'transport select <transport>'.                                                 
jtag_ntrst_delay: 100                                                           
cortex_m reset_config sysresetreq                                               
sh_load                                                                         
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED                     
Info : clock speed 3000 kHz                                                     
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba
00, ver: 0x4)                                                                   
Info : wmcore.cpu: hardware has 6 breakpoints, 4 watchpoints                    
Info : JTAG tap: wmcore.cpu tap/device found: 0x4ba00477 (mfg: 0x23b, part: 0xba
00, ver: 0x4)                                                                   
target state: halted                                                            
target halted due to debug-request, current mode: Thread                        
xPSR: 0x01000000 pc: 0x00007f14 msp: 0x20001000                                 
auto erase enabled                                                              
Info : Found flash device 'win w25q32fv' ID 0x001640ef                          
wrote 1376256 bytes from file C:/Users/DavidJ/dev/repos/aws_starter_sdk.git/aws_
starter_sdk-2015_11_04.blob in 17.735994s (75.778 KiB/s)                        
shutdown command invoked                                                        
Resetting flash to factory settings done...

**Comment by rahulgm** [comment]
Yes, the device can be recovered. There seems to be an OpenOCD error LIBUSB_ERROR_NOT_SUPPORTED that could be the cause for improper flashing. We haven't observed this on our Win10 setup, but will try a few more machines and get back to you.

**Comment by anujdeshpande** [comment]
Hey @truedat101 just to be sure, could you also check the md5 checksum using [this](http://www.microsoft.com/en-us/download/details.aspx?id=11533) Microsoft tool

I have added the checksum value to the release info [here](https://github.com/marvell-iot/aws_starter_sdk/releases)

**Comment by truedat101** [comment]
I will try.

**Comment by truedat101** [comment]
Will try this again on the windows side.  I have a new clean system (WIn10) to test with.

**Comment by truedat101** [comment]
Still same batch of problems with LIBUSB_ERROR_NOT_SUPPORTED.  Perhaps a driver issue?

**Comment by truedat101** [comment]
The error gets reported regardless of whether or not it works.  Is it safe to say this is a harmless warning?

A few details to note:

- Windows Firewall pops up when the flasher runs, so it is important to allow it
- The choice of a cygwin is important, though cygwin can be a hassle to install (downloader, selecting mirror, choosing components).  I have confirmed that the current Cmder (alternative to cygwin) won't work, and neither will ConEMU.  Babun ( http://babun.github.io/ ) will work and simplifies the process of grabbing cygwin and major components that are needed.

**Comment by truedat101** [comment]
I'd suggest this could be closed if the appropriate documentation of the 'harmless' nature of the errors can be done.
