### ISSUE TITLE
Windows Host Setup WIKI missing instructions on Serial Debug Setup

### ISSUE THREAD

**Issue by truedat101** [marvell-iot/aws_starter_sdk#9]
If you look under here: https://github.com/marvell-iot/aws_starter_sdk/wiki/Windows-Development-Host-Setup

It does not include set up instructions for serial debug setup.  I realize the setup is pretty typical or common in terms of what might already work other MRVL SoCs.  However, it might be useful to provide these instructions for Windows (probably Linux and esp. Mac).

**Comment by msaksena** [comment]
Yes, of course. We will get that fixed.

**Comment by kedars** [comment]
Fixed!
